# Generated by Django 4.2.20 on 2025-05-20 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Categoria')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Marca')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome do produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade em estoque')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
                ('status', models.CharField(default='activo', max_length=20, verbose_name='Status')),
                ('codigo_barra', models.CharField(max_length=50, unique=True, verbose_name='Código de barras')),
                ('avaliacao', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Avaliacao')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='products.marca')),
            ],
        ),
    ]
