# Generated by Django 4.2.20 on 2025-05-20 15:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco unitario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pendente', max_length=20, verbose_name='Status do pedido')),
                ('data_pedido', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pedido')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor total')),
            ],
        ),
        migrations.CreateModel(
            name='TipoTransacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Tipo de transacao')),
                ('descricao', models.TextField(blank=True, verbose_name='Descricao')),
            ],
        ),
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd_produtos', models.IntegerField(verbose_name='Quantidade de produtos')),
                ('valor_transacao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da transacao')),
                ('data_transacao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data da Transacao')),
                ('status', models.CharField(default='iniciada', max_length=20, verbose_name='Status da transacao')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='orders.pedido')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transacoes', to='orders.tipotransacao')),
            ],
        ),
    ]
